// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface loginResponse {
    id:          string;
    created_at:  string;
    firstName:   string;
    lastName:    string;
    password:    string;
    phoneNumber: number;
}
